[project]
name = "phs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ko.libri", email = "entengelb@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cyclopts>=4.25.3",
    "pyinfra>=3.10.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
phs = "phs.cli:app"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
